use schema DATASYNTHESIS;
DROP TABLE IF EXISTS REFDATA_STATUS;
CREATE TABLE REFDATA_STATUS (
       STATUSID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_REFDATA_STATUS PRIMARY KEY,
       STATUSDESCRIPTION VARCHAR(45) NOT NULL,
       CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
       CREATEDUSER VARCHAR(20)
);

DROP TABLE IF EXISTS DATABUILT_DATASTRUCTUES;
CREATE TABLE DATABUILT_DATASTRUCTUES (
    DATASTRUCTURECOREID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_DATABUILT_DATASTRUCTURES PRIMARY KEY,
    DATASTRUCTURENAME VARCHAR(29),
    DATASTRUCTUREDETAILS TEXT,
    CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUSID NUMBER DEFAULT 1,
    REGISTEREDAPP CHAR(38),
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS DATATIER;
CREATE TABLE DATATIER (
    DATATIERID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_DATATIER PRIMARY KEY,
    BASEVALUE VARCHAR(99),
    SUPPORTINGVALUE1 VARCHAR(169),
    SUPPORTINGVALUE2 VARCHAR(50),
    SUPPORTINGVALUE3 VARCHAR(50),
    SUPPORTINGVALUE4 VARCHAR(50),
    SUPPORTINGVALUE5 VARCHAR(50),
    SUPPORTINGVALUE6 VARCHAR(50),
    SUPPORTINGVALUE7 VARCHAR(50),
    DATAATTRIBUTEID NUMBER,
    DATAGENTYPEID NUMBER,
    CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUSID NUMBER DEFAULT 1,
    CREATEDUSER VARCHAR(20),
    REGISTEREDAPP CHAR(38),
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS DATAMODEL_APIS;
CREATE TABLE DATAMODEL_APIS (
    APIID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_APIS PRIMARY KEY,
    TECHNOLOGY VARCHAR(30),
    BASEURLLOCATION VARCHAR(99),
    APINAME VARCHAR(79),
    CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUSID NUMBER DEFAULT 1,
    PURPOSE VARCHAR(49),
    DATMODEL_TABLENAME VARCHAR(99),
    APIPARAMS VARCHAR(59),
    APIEXAMPLE VARCHAR(149),
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS DATAMODEL_DATATABLES;
CREATE TABLE DATAMODEL_DATATABLES (
    TABLENAME VARCHAR(64) CONSTRAINT PK_DATAMODEL_DATATABLES PRIMARY KEY,
    TABLEINFORMATION VARCHAR(249),
    STATUSID NUMBER DEFAULT 1,
    CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DATADOMAIN VARCHAR(64),
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS DATAMODEL_DOMAIN;
CREATE TABLE DATAMODEL_DOMAIN (
     DOMAINNAME VARCHAR(64) CONSTRAINT PK_DATAMODEL_DOMAIN PRIMARY KEY,
     DOMAININFORMATION VARCHAR(249),
     STATUSID NUMBER DEFAULT 1,
     CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
     FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS PLATFORM_DATAATTRIBUTES;
CREATE TABLE PLATFORM_DATAATTRIBUTES (
      PLATFORMDATAATTRIBUTESID NUMBER autoincrement start 1 increment 1  CONSTRAINT PK_PLATFORM_DATAATTRIBUTES PRIMARY KEY,
      DATAATTRIBUTENAME VARCHAR(50),
      SENSITIVITYFLAGID NUMBER,
      CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
      STATUSID NUMBER DEFAULT 1,
      CREATEDUSER VARCHAR(20),
      PLATFORMDATAATTRIBUTEGUID CHAR(38),
      REGISTEREDAPP CHAR(38),
      PLATFORMTABLENAME VARCHAR(38),
      FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS PLATFORM_DATAGENERATION;
CREATE TABLE PLATFORM_DATAGENERATION (
      DATAGENTYPEID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_REFDATA_DATAGENTYPES PRIMARY KEY,
      DATAGENTYPEDESCRIPTION VARCHAR(65),
      DEFINITION VARCHAR(255),
      DATAATTRIBUTEID NUMBER,
      CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
      STATUSID NUMBER DEFAULT 1,
      CREATEDUSER VARCHAR(20),
      FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS PLATFORM_DATASTRUCTURES;
CREATE TABLE PLATFORM_DATASTRUCTURES (
    PLATFORMDATASTRUCTURESID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_PLATFORM_CONFIG_DATASTRUCTURES PRIMARY KEY,
    DATASTRUCTURENAME VARCHAR(50),
    SENSITIVITYFLAGID NUMBER,
    CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUSID NUMBER DEFAULT 1,
    CREATEDUSER VARCHAR(20),
    PLATFORMDATASTRUCTURESGUID CHAR(38),
    REGISTEREDAPP CHAR(38),
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS PLATFORM_DATASTRUCTURES_DTL;
CREATE TABLE PLATFORM_DATASTRUCTURES_DTL (
    PLATFORMDATASTRUCTURESDTLID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_PLATFORM_CONFIG_DATASTRUCTURES_DTL PRIMARY KEY,
    PLATFORMDATASTRUCTURESID NUMBER,
    COMPOSITEDATASTRUCTURENAME VARCHAR(50),
    SENSITIVITYFLAGID NUMBER,
    CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUSID NUMBER DEFAULT 1,
    CREATEDUSER VARCHAR(20),
    PLATFORMDATASTRUCTURESTODATAATTRIBUTESGUID CHAR(38),
    REGISTEREDAPP CHAR(38),
    PLATFORMDATAATTRIBUTESID INT,
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);


DROP TABLE IF EXISTS REFDATA_APPLICATION;
CREATE TABLE REFDATA_APPLICATION (
     APPGUID CHAR(38) DEFAULT UUID_STRING() CONSTRAINT PK_REFDATA_APPLICATION PRIMARY KEY,
     APPLICATIONCUSTOMCODE VARCHAR(15),
     APPLICATIONDESC VARCHAR(50),
     CREATEDUSER VARCHAR(20),
     CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
     STATUSID NUMBER DEFAULT 1,
     VENDORID NUMBER,
     INDUSTRY_OID VARCHAR(49),
     ORGANIZATION_UID VARCHAR(49),
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_CODESET;
CREATE TABLE REFDATA_CODESET (
    CODESETSID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_REFDATA_CODESET PRIMARY KEY,
    CODESETNAME VARCHAR(50),
    INDUSTRYSTD VARCHAR(6),
    STATUSID NUMBER DEFAULT 1,
    CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATEDUSER VARCHAR(20),
    CODESETGUID CHAR(38),
    FIELDMAPPING VARCHAR(40),
    SENSITIVITYFLAGID NUMBER,
    EXTERNALTABLEID VARCHAR(20),
    EXTERNALNOTES VARCHAR(149),
    EXTERNALLINK VARCHAR(99),
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_CODESETS_CROSSMAPS;
CREATE TABLE REFDATA_CODESETS_CROSSMAPS (
    CODESETCROSSMAPID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_REFDATA_CODESETS_CROSSMAPS PRIMARY KEY,
    IMPLCODESETSID INT NOT NULL,
    CODESETTOAPPLICATIONID BIGINT,
    TERMINOLOGYSTDTO NUMBER,
    CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUSID NUMBER DEFAULT 1,
    CREATEDUSER VARCHAR(20),
    TRANSFORMCODEVALUE VARCHAR(40),
    TRANSFORMCODEDESC VARCHAR(129),
    ORIGINALCODEVALUE VARCHAR(40),
    ORIGINALCODEDESC VARCHAR(40),
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_COUNTRIES;
CREATE TABLE REFDATA_COUNTRIES (
    COUNTRYID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_REFDATA_COUNTRIES PRIMARY KEY,
    IDD VARCHAR(5),
    COUNTRYNAME VARCHAR(59),
    CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUSID NUMBER DEFAULT 1,
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);


DROP TABLE IF EXISTS REFDATA_DEVICETYPES;
CREATE TABLE REFDATA_DEVICETYPES (
    DEVICETYPEID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_REFDATA_DEVICETYPES PRIMARY KEY,
    DEVICETYPE VARCHAR(30),
    CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUSID NUMBER DEFAULT 1,
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_INDUSTRIES;
CREATE TABLE REFDATA_INDUSTRIES (
    INDUSTRYID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_REFDATA_INDUSTRIES PRIMARY KEY,
    INDUSTRYNAME VARCHAR(45),
    CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUSID NUMBER DEFAULT 1,
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_INDUSTRIESTOBUSINESS;
CREATE TABLE REFDATA_INDUSTRIESTOBUSINESS (
    INDUSTRYTOBUSINESSID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_REFDATA_INDUSTRIESTOBUSINESS PRIMARY KEY,
    INDUSTRYID NUMBER,
    BUSINESSAREA VARCHAR(50),
    CREATEDDATE TIMESTAMPNTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUSID NUMBER DEFAULT 1,
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_INDUSTRYSTD;
CREATE TABLE REFDATA_INDUSTRYSTD (
    INDUSTRYSTD VARCHAR(6) CONSTRAINT PK_REFDATA_INDUSTRYSTD PRIMARY KEY,
    INDUSTRYSTDDESC VARCHAR(30),
    CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUSID NUMBER DEFAULT 1,
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_LEGALENTITIES;
CREATE TABLE REFDATA_LEGALENTITIES (
     LEGALENTITYGUID CHAR(38) DEFAULT UUID_STRING() CONSTRAINT PK_REFDATA_LEGALENTITIES_GROUPERS PRIMARY KEY,
     LOCATIONNAME VARCHAR(50),
     ADDRESS VARCHAR(75),
     CITY VARCHAR(60),
     STATEID VARCHAR(2),
     ZIPCODE VARCHAR(12),
     CREATEDUSER VARCHAR(20),
     STATUSID NUMBER DEFAULT 1,
     CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
     LOCATIONURL VARCHAR(99),
     LOCATIONPHONE VARCHAR(12),
     FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_OPERATIONTYPE;
CREATE TABLE REFDATA_OPERATIONTYPE (
     OPERATIONTYPEID VARCHAR(7) CONSTRAINT PK_REFDATA_OPERATIONTYPE PRIMARY KEY,
     OPERATIONTYPENAME VARCHAR(60),
     CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
     STATUSID NUMBER DEFAULT 1,
     FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_ORGANIZATION;
CREATE TABLE REFDATA_ORGANIZATION (
      ORGANIZATIONGUID CHAR(38) DEFAULT UUID_STRING() CONSTRAINT PK_REFDATA_ORGANIZATION PRIMARY KEY,
      ORGANIZATIONINTERNALCODE VARCHAR(10),
      ORGANIZATIONINTERNALID VARCHAR(10),
      ORGANIZATIONNAME VARCHAR(50),
      ADDRESS VARCHAR(75),
      CITY VARCHAR(60),
      STATEID VARCHAR(2),
      ZIPCODE VARCHAR(12),
      CREATEDUSER VARCHAR(20),
      STATUSID NUMBER DEFAULT 1,
      CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
      LEGALENTITYGUID CHAR(38),
      FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_PROFESSIONTYPES;
CREATE TABLE REFDATA_PROFESSIONTYPES (
       PROFESSIONTYPEID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_REFDATA_PROFESSIONTYPES PRIMARY KEY,
       PROFESSIONTYPENAME VARCHAR(65),
       CREATEDUSER VARCHAR(20),
       CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
       STATUSID NUMBER DEFAULT 1,
       FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_REGEXTYPES;
CREATE TABLE REFDATA_REGEXTYPES (
       IMPLREGEXTYPEID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_REFDATA_REGEXTYPES PRIMARY KEY,
       REGEXTYPEDESC VARCHAR(69),
       CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
       STATUSID NUMBER DEFAULT 1,
       ORGANIZATIONID CHAR(38),
       APPLICATIONID CHAR(38),
       FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_RULESETS;
CREATE TABLE REFDATA_RULESETS (
       RULEID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_REFDATA_RULESETS PRIMARY KEY,
       RULENAME VARCHAR(65),
       CREATEDUSER VARCHAR(20),
       CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
       STATUSID NUMBER DEFAULT 1,
       FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_RULESETSDEFINITIONS; 
CREATE TABLE REFDATA_RULESETSDEFINITIONS (
       RULESETDEFINITIONSID CHAR(38) DEFAULT UUID_STRING() CONSTRAINT PK_REFDATA_RULESETSDEFINITIONS PRIMARY KEY,
       RULESETDEFINITIONNAME VARCHAR(50),
       RULESETID NUMBER,
       STEPORDERID NUMBER,
       OPERATIONTYPEID VARCHAR(7),
       RULESETDEFVALUE CHAR(40),
       STATUSID NUMBER DEFAULT 1,
       CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
       EFFECTIVEDATE DATETIME,
       APPLICATIONID CHAR(38),
       TERMDATE DATETIME,
       DATAATTRIBUTEID INT,
       FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_SENSITIVITYFLAG;
CREATE TABLE REFDATA_SENSITIVITYFLAG (
       SENSITIVEFLAGID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_REFDATA_SENSITIVITYFLAG PRIMARY KEY,
       SENSITIVEFLAGDESC VARCHAR(30),
       CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
       STATUSID NUMBER DEFAULT 1,
       FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_TERMINOLOGYSTD;
CREATE TABLE REFDATA_TERMINOLOGYSTD (
        TERMINOLOGYSTDID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_REFDATA_TERMINOLOGYSTD PRIMARY KEY,
        TERMINOLOGYSTD VARCHAR(25) NOT NULL,
        TERMINOLOGYSTDVERSION VARCHAR(10) NOT NULL,
        TERMINOLOGYSTDDESC VARCHAR(129),
        CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        STATUSID NUMBER DEFAULT 1,
        FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_TIMEZONES;
CREATE TABLE REFDATA_TIMEZONES (
        TIMEZONEVALUE VARCHAR(3) CONSTRAINT PK_REFDATA_TIMEZONES PRIMARY KEY,
        TIMEZONEDESC VARCHAR(25),
        CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        STATUSID NUMBER DEFAULT 1,
        FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_USSTATES;
CREATE TABLE REFDATA_USSTATES (
        STATEID VARCHAR(2) CONSTRAINT PK_REFDATA_USSTATES PRIMARY KEY,
        STATEDESCRIPTION VARCHAR(65),
        LATTITUDE VARCHAR(12),
        LONGITUDE VARCHAR(12),
        CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        STATUSID NUMBER DEFAULT 1,
        CREATEDUSER VARCHAR(20),
        FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS REFDATA_VENDOR;
CREATE TABLE REFDATA_VENDOR (
        VENDORID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_REFDATA_VENDOR PRIMARY KEY,
        VENDORNAME VARCHAR(50),
        CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        STATUSID NUMBER DEFAULT 1,
        CREATEDUSER VARCHAR(20),
        VENDORGUID CHAR(38),
        FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS TERMS_CODESET_INDUSTRYSTD;
CREATE TABLE TERMS_CODESET_INDUSTRYSTD (
    TERMCODESETID NUMBER autoincrement start 1 increment 1 CONSTRAINT PK_TERMS_CODESET_INDUSTRYSTD PRIMARY KEY,
    CODESETSID INT NOT NULL,
    CREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUSID NUMBER DEFAULT 1,
    CODEVALUE VARCHAR(20),
    CODEDESC VARCHAR(129),
    INDUSTRYSTD VARCHAR(6),
    TERMINOLOGYSTDID NUMBER,
    FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);

DROP TABLE IF EXISTS TERMS_UMLS_MRCONOSO;
CREATE TABLE TERMS_UMLS_MRCONOSO (
     CUI CHAR(8) NOT NULL,
     LAT CHAR(3) NOT NULL,
     TS CHAR(1) NOT NULL,
     LUI VARCHAR(10) NOT NULL,
     STT VARCHAR(3) NOT NULL,
     SUI VARCHAR(10) NOT NULL,
     ISPREF CHAR(1) NOT NULL,
     AUI VARCHAR(9) NOT NULL,
     SAUI VARCHAR(50),
     SCUI VARCHAR(100),
     SDUI VARCHAR(100),
     SAB VARCHAR(20) NOT NULL,
     TTY VARCHAR(20) NOT NULL,
     CODE VARCHAR(100) NOT NULL,
     STR VARCHAR(3000) NOT NULL,
     SRL VARCHAR(25) NOT NULL,
     SUPPRESS CHAR(1) NOT NULL,
     STATUSID NUMBER DEFAULT 1,
     CREATEDDATE TIMESTAMP_NTZ default CURRENT_TIMESTAMP(),
     FOREIGN KEY(STATUSID) REFERENCES REFDATA_STATUS(STATUSID)
);
