
DROP TABLE IF EXISTS REFDATA_STATUS;
CREATE TABLE REFDATA_STATUS (
       STATUSID integer NOT NULL,
       STATUSDESCRIPTION string,
       CREATEDDATE DATE
);
ALTER TABLE REFDATA_STATUS ADD CONSTRAINT xpk_REFDATA_STATUS PRIMARY KEY (STATUSID);

DROP TABLE IF EXISTS DATAMODEL_APIS;
CREATE TABLE DATAMODEL_APIS (
     APIID INTEGER NOT NULL,
     TECHNOLOGY STRING,
     BASEURLLOCATION STRING,
     APINAME STRING,
     CREATEDDATE DATE,
     STATUSID INTEGER,
     PURPOSE STRING,
     DATMODEL_TABLENAME STRING,
     APIPARAMS STRING,
     APIEXAMPLE STRING
);
ALTER TABLE DATAMODEL_APIS ADD CONSTRAINT xpk_DATAMODEL_APIS PRIMARY KEY (APIID);

DROP TABLE IF EXISTS DATAMODEL_DATATABLES;
CREATE TABLE DATAMODEL_DATATABLES (
    TABLENAME STRING NOT NULL,
    TABLEINFORMATION STRING,
    STATUSID INTEGER,
    CREATEDDATE TIMESTAMP,
    DOMAIN STRING
);
ALTER TABLE DATAMODEL_DATATABLES ADD CONSTRAINT xpk_DATAMODEL_DATATABLES PRIMARY KEY (TABLENAME);

DROP TABLE IF EXISTS DATAMODEL_DOMAIN;
CREATE TABLE DATAMODEL_DOMAIN (
     DOMAINNAME STRING NOT NULL,
     DOMAININFORMATION STRING,
     STATUSID INTEGER,
     CREATEDDATE TIMESTAMP
);
ALTER TABLE DATAMODEL_DOMAIN ADD CONSTRAINT xpk_DATAMODEL_DOMAIN PRIMARY KEY (DOMAINNAME);

DROP TABLE IF EXISTS DATABUILT_DATASTRUCTUES;
DROP TABLE IF EXISTS DATABUILT_DATASTRUCTURES;
CREATE TABLE DATABUILT_DATASTRUCTURES (
    DATASTRUCTURECOREID INTEGER NOT NULL,
    DATASTRUCTURENAME STRING,
    DATASTRUCTUREDETAILS STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    REGISTEREDAPP STRING
);
ALTER TABLE DATABUILT_DATASTRUCTURES ADD CONSTRAINT xpk_DATABUILT_DATASTRUCTURES PRIMARY KEY (DATASTRUCTURECOREID);

DROP TABLE IF EXISTS DATAEXISTING_ABABANKING;
CREATE TABLE DATAEXISTING_ABABANKING (
    ABABANKINGID INTEGER NOT NULL,
    ROUTINGNUMBER STRING,
    TELEGRAPHICNAME STRING,
    CUSTOMERNAME STRING,
    CITY STRING,
    STATECODE STRING,
    ZIPCODE STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_ABABANKING ADD CONSTRAINT xpk_DATAEXISTING_ABABANKING PRIMARY KEY (ABABANKINGID);

DROP TABLE IF EXISTS DATAEXISTING_AREACODE;
CREATE TABLE DATAEXISTING_AREACODE (
    AREACODEID INTEGER NOT NULL,
    AREACODEVALUE STRING,
    TIMEZONE STRING,
    STATECODE STRING,
    CREATEDDATE DATE,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_AREACODE ADD CONSTRAINT xpk_DATAEXISTING_AREACODE PRIMARY KEY (AREACODEID);

DROP TABLE IF EXISTS DATAEXISTING_AREACODEINTL;
CREATE TABLE DATAEXISTING_AREACODEINTL (
    IDDCODE STRING NOT NULL,
    COUNTRYID INTEGER,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_AREACODEINTL ADD CONSTRAINT xpk_DATAEXISTING_AREACODEINTL PRIMARY KEY (IDDCODE);

DROP TABLE IF EXISTS DATAEXISTING_COMPANIES;
CREATE TABLE DATAEXISTING_COMPANIES (
    COMPANIESID INTEGER NOT NULL,
    COMPANYNAME STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_COMPANIES ADD CONSTRAINT xpk_DATAEXISTING_COMPANIES PRIMARY KEY (COMPANIESID);

DROP TABLE IF EXISTS DATAEXISTING_NAMEFIRST;
CREATE TABLE DATAEXISTING_NAMEFIRST (
    FIRSTNAMEID INTEGER NOT NULL,
    FIRSTNAME STRING,
    GENDER STRING,
    STATUSID INTEGER,
    CREATEDDATE TIMESTAMP,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_NAMEFIRST ADD CONSTRAINT xpk_DATAEXISTING_NAMEFIRST PRIMARY KEY (FIRSTNAMEID);

DROP TABLE IF EXISTS DATAEXISTING_NAMELAST;
CREATE TABLE DATAEXISTING_NAMELAST (
    LASTNAMEID INTEGER NOT NULL,
    LASTNAME STRING,
    STATUSID INTEGER,
    CREATEDDATE TIMESTAMP,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_NAMELAST ADD CONSTRAINT xpk_DATAEXISTING_NAMELAST PRIMARY KEY (LASTNAMEID);

DROP TABLE IF EXISTS DATAEXISTING_PROFESSION;
CREATE TABLE DATAEXISTING_PROFESSION (
    PROFESSIONID INTEGER NOT NULL,
    PROFESSIONNAME STRING,
    STATUSID INTEGER,
    CREATEDDATE TIMESTAMP,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_PROFESSION ADD CONSTRAINT xpk_DATAEXISTING_PROFESSION PRIMARY KEY (PROFESSIONID);

DROP TABLE IF EXISTS DATAEXISTING_UPCCODES;
CREATE TABLE DATAEXISTING_UPCCODES (
    UPCCODEID INTEGER NOT NULL,
    UPCCODENAME STRING,
    UPCPRODUCTNAME STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_UPCCODES ADD CONSTRAINT xpk_DATAEXISTING_UPCCODES PRIMARY KEY (UPCCODEID);

DROP TABLE IF EXISTS DATAEXISTING_ZIPCODEINTL;
CREATE TABLE DATAEXISTING_ZIPCODEINTL (
    ZIPCODEINTNLID INTEGER NOT NULL,
    ZIPCODE STRING,
    ZIPCODETYPE STRING,
    CITY STRING,
    COUNTRY STRING,
    LATTITUDE STRING,
    LONGITUDE STRING,
    LOCATION STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_ZIPCODEINTL ADD CONSTRAINT xpk_DATAEXISTING_ZIPCODEINTL PRIMARY KEY (ZIPCODEINTNLID);

DROP TABLE IF EXISTS ZIPCODEUS;
CREATE TABLE DATAEXISTING_ZIPCODEUS (
    ZIPCODEID INTEGER NOT NULL,
    ZIPCODE STRING,
    ZIPCODETYPE STRING,
    CITY STRING,
    STATECODE STRING,
    LATTITUDE STRING,
    LONGITUDE STRING,
    LCTN STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_ZIPCODEUS ADD CONSTRAINT xpk_DATAEXISTING_ZIPCODEUS PRIMARY KEY (ZIPCODEID);
