DROP TABLE IF EXISTS REFDATA_APPLICATION;
CREATE TABLE REFDATA_APPLICATION (
	APPGUID STRING NOT NULL,
	APPLICATIONCUSTOMCODE STRING,
	APPLICATIONDESC STRING,
	CREATEDUSER STRING,
	CREATEDDATE TIMESTAMP,
	STATUSID INTEGER,
	VENDORID INTEGER,
	INDUSTRY_OID STRING,
	ORGANIZATION_UID STRING
);
ALTER TABLE REFDATA_APPLICATION ADD CONSTRAINT xpk_REFDATA_APPLICATION PRIMARY KEY (APPGUID);

DROP TABLE IF EXISTS REFDATA_DATAGENTYPES;
CREATE TABLE REFDATA_DATAGENTYPES (
	DATAGENTYPEID INTEGER NOT NULL,
	DATAGENTYPEDESCRIPTION STRING,
	DEFINITION STRING,
	DATAATTRIBUTEID INTEGER,
	CREATEDDATE TIMESTAMP,
	STATUSID INTEGER,
	CREATEDUSER STRING
);
ALTER TABLE REFDATA_DATAGENTYPES ADD CONSTRAINT xpk_REFDATA_DATAGENTYPES PRIMARY KEY (DATAGENTYPEID);

DROP TABLE IF EXISTS REFDATA_DEVICETYPES;
CREATE TABLE REFDATA_DEVICETYPES (
	DEVICETYPEID INTEGER NOT NULL,
	DEVICETYPE STRING,
	CREATEDDATE TIMESTAMP,
	STATUSID INTEGER
);
ALTER TABLE REFDATA_DEVICETYPES ADD CONSTRAINT xpk_REFDATA_DEVICETYPES PRIMARY KEY (DEVICETYPEID);

DROP TABLE IF EXISTS REFDATA_LEGALENTITIES;
CREATE TABLE REFDATA_LEGALENTITIES (
	LEGALENTITYGUID STRING NOT NULL,
	LOCATIONNAME STRING,
	ADDRESS STRING,
	CITY STRING,
	STATEID STRING,
	ZIPCODE STRING,
	CREATEDUSER STRING,
	STATUSID INTEGER,
	CREATEDDATE TIMESTAMP,
	LOCATIONURL STRING,
	LOCATIONPHONE STRING
);
ALTER TABLE REFDATA_LEGALENTITIES ADD CONSTRAINT xpk_REFDATA_LEGALENTITIES PRIMARY KEY (LEGALENTITYGUID);

DROP TABLE IF EXISTS REFDATA_ORGANIZATION;
CREATE TABLE REFDATA_ORGANIZATION (
	ORGANIZATIONGUID STRING NOT NULL,
	ORGANIZATIONINTERNALCODE STRING,
	ORGANIZATIONINTERNALID STRING,
	ORGANIZATIONNAME STRING,
	ADDRESS STRING,
	CITY STRING,
	STATEID STRING,
	ZIPCODE STRING,
	CREATEDUSER STRING,
	STATUSID INTEGER,
	CREATEDDATE TIMESTAMP,
	LEGALENTITYGUID STRING
);
ALTER TABLE REFDATA_ORGANIZATION ADD CONSTRAINT xpk_REFDATA_ORGANIZATION PRIMARY KEY (ORGANIZATIONGUID);

DROP TABLE IF EXISTS REFDATA_PLATFORMPARAMS;
CREATE TABLE REFDATA_PLATFORMPARAMS (
	PLATFORMPARAMSID INTEGER NOT NULL,
	PLATFORMPARAMVALUES STRING,
	PLATFORMPARAMDESC STRING,
	CREATEDDATE TIMESTAMP,
	STATUSID INTEGER
);
ALTER TABLE REFDATA_PLATFORMPARAMS ADD CONSTRAINT xpk_REFDATA_PLATFORMPARAMS PRIMARY KEY (PLATFORMPARAMSID);

DROP TABLE IF EXISTS REFDATA_PLATFORMPARAMSTODATAATTRIBUTES;
CREATE TABLE REFDATA_PLATFORMPARAMSTODATAATTRIBUTES (
	PLATFORMPARAMSTODATAATTRIBUTEID INTEGER NOT NULL,
	PLATFORMPARAMSID INTEGER,
	DATAATTRIBUTEID INTEGER,
	CREATEDDATE TIMESTAMP,
	STATUSID INTEGER,
	REGISTEREDAPP STRING
);
ALTER TABLE REFDATA_PLATFORMPARAMSTODATAATTRIBUTES ADD CONSTRAINT xpk_REFDATA_PLATFORMPARAMSTODATAATTRIBUTES PRIMARY KEY (PLATFORMPARAMSTODATAATTRIBUTEID);

DROP TABLE IF EXISTS REFDATA_REGEXTYPES;
CREATE TABLE REFDATA_REGEXTYPES (
	IMPLREGEXTYPEID INTEGER NOT NULL,
	REGEXTYPEDESC STRING,
	CREATEDDATE TIMESTAMP,
	STATUSID INTEGER,
	ORGANIZATIONID STRING,
	APPLICATIONID STRING
);
ALTER TABLE REFDATA_REGEXTYPES ADD CONSTRAINT xpk_REFDATA_REGEXTYPES PRIMARY KEY (IMPLREGEXTYPEID);

DROP TABLE IF EXISTS REFDATA_SENSITIVITYFLAG;
CREATE TABLE REFDATA_SENSITIVITYFLAG (
	SENSITIVEFLAGID INTEGER NOT NULL,
	SENSITIVEFLAGDESC STRING,
	CREATEDDATE TIMESTAMP,
	STATUSID INTEGER
);
ALTER TABLE REFDATA_SENSITIVITYFLAG ADD CONSTRAINT xpk_REFDATA_SENSITIVITYFLAG PRIMARY KEY (SENSITIVEFLAGID);

DROP TABLE IF EXISTS REFDATA_TIMEZONES;
CREATE TABLE REFDATA_TIMEZONES (
	TIMEZONEVALUE STRING NOT NULL,
	TIMEZONEDESC STRING,
	CREATEDDATE TIMESTAMP,
	STATUSID INTEGER
);
ALTER TABLE REFDATA_TIMEZONES ADD CONSTRAINT xpk_REFDATA_TIMEZONES PRIMARY KEY (TIMEZONEVALUE);

DROP TABLE IF EXISTS REFDATA_USSTATES;
CREATE TABLE REFDATA_USSTATES (
	STATEID STRING NOT NULL,
	STATEDESCRIPTION STRING,
	LATTITUDE STRING,
	LONGITUDE STRING,
	CREATEDDATE TIMESTAMP,
	STATUSID INTEGER,
	CREATEDUSER STRING
);
ALTER TABLE REFDATA_USSTATES ADD CONSTRAINT xpk_REFDATA_USSTATES PRIMARY KEY (STATEID);

DROP TABLE IF EXISTS REFDATA_VENDOR;
CREATE TABLE REFDATA_VENDOR (
	VENDORID INTEGER NOT NULL,
	VENDORNAME STRING,
	CREATEDDATE TIMESTAMP,
	STATUSID INTEGER,
	CREATEDUSER STRING,
	VENDORGUID STRING
);
ALTER TABLE REFDATA_VENDOR ADD CONSTRAINT xpk_REFDATA_VENDOR PRIMARY KEY (VENDORID);

DROP TABLE IF EXISTS REFDATA_STATUS;
CREATE TABLE REFDATA_STATUS (
       STATUSID integer NOT NULL,
       STATUSDESCRIPTION string,
       CREATEDDATE DATE,
       CREATEDUSER STRING
);
ALTER TABLE REFDATA_STATUS ADD CONSTRAINT xpk_REFDATA_STATUS PRIMARY KEY (STATUSID);

DROP TABLE IF EXISTS DATAMODEL_APIS;
CREATE TABLE DATAMODEL_APIS (
     APIID INTEGER NOT NULL,
     TECHNOLOGY STRING,
     BASEURLLOCATION STRING,
     APINAME STRING,
     CREATEDDATE DATE,
     STATUSID INTEGER,
     PURPOSE STRING,
     DATMODEL_TABLENAME STRING,
     APIPARAMS STRING,
     APIEXAMPLE STRING
);
ALTER TABLE DATAMODEL_APIS ADD CONSTRAINT xpk_DATAMODEL_APIS PRIMARY KEY (APIID);

DROP TABLE IF EXISTS DATAMODEL_DATATABLES;
CREATE TABLE DATAMODEL_DATATABLES (
    TABLENAME STRING NOT NULL,
    TABLEINFORMATION STRING,
    STATUSID INTEGER,
    CREATEDDATE TIMESTAMP,
    DOMAIN STRING
);
ALTER TABLE DATAMODEL_DATATABLES ADD CONSTRAINT xpk_DATAMODEL_DATATABLES PRIMARY KEY (TABLENAME);

DROP TABLE IF EXISTS DATAMODEL_DOMAIN;
CREATE TABLE DATAMODEL_DOMAIN (
     DOMAINNAME STRING NOT NULL,
     DOMAININFORMATION STRING,
     STATUSID INTEGER,
     CREATEDDATE TIMESTAMP
);
ALTER TABLE DATAMODEL_DOMAIN ADD CONSTRAINT xpk_DATAMODEL_DOMAIN PRIMARY KEY (DOMAINNAME);

DROP TABLE IF EXISTS DATABUILT_DATASTRUCTUES;
DROP TABLE IF EXISTS DATABUILT_DATASTRUCTURES;
CREATE TABLE DATABUILT_DATASTRUCTURES (
    DATASTRUCTURECOREID INTEGER NOT NULL,
    DATASTRUCTURENAME STRING,
    DATASTRUCTUREDETAILS STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    REGISTEREDAPP STRING
);
ALTER TABLE DATABUILT_DATASTRUCTURES ADD CONSTRAINT xpk_DATABUILT_DATASTRUCTURES PRIMARY KEY (DATASTRUCTURECOREID);

DROP TABLE IF EXISTS DATAEXISTING_ABABANKING;
CREATE TABLE DATAEXISTING_ABABANKING (
    ABABANKINGID INTEGER NOT NULL,
    ROUTINGNUMBER STRING,
    TELEGRAPHICNAME STRING,
    CUSTOMERNAME STRING,
    CITY STRING,
    STATECODE STRING,
    ZIPCODE STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_ABABANKING ADD CONSTRAINT xpk_DATAEXISTING_ABABANKING PRIMARY KEY (ABABANKINGID);

DROP TABLE IF EXISTS DATAEXISTING_AREACODE;
CREATE TABLE DATAEXISTING_AREACODE (
    AREACODEID INTEGER NOT NULL,
    AREACODEVALUE STRING,
    TIMEZONE STRING,
    STATECODE STRING,
    CREATEDDATE DATE,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_AREACODE ADD CONSTRAINT xpk_DATAEXISTING_AREACODE PRIMARY KEY (AREACODEID);

DROP TABLE IF EXISTS DATAEXISTING_AREACODEINTL;
CREATE TABLE DATAEXISTING_AREACODEINTL (
    IDDCODE STRING NOT NULL,
    COUNTRYID INTEGER,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_AREACODEINTL ADD CONSTRAINT xpk_DATAEXISTING_AREACODEINTL PRIMARY KEY (IDDCODE);

DROP TABLE IF EXISTS DATAEXISTING_COMPANIES;
CREATE TABLE DATAEXISTING_COMPANIES (
    COMPANIESID INTEGER NOT NULL,
    COMPANYNAME STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_COMPANIES ADD CONSTRAINT xpk_DATAEXISTING_COMPANIES PRIMARY KEY (COMPANIESID);

DROP TABLE IF EXISTS DATAEXISTING_NAMEFIRST;
CREATE TABLE DATAEXISTING_NAMEFIRST (
    FIRSTNAMEID INTEGER NOT NULL,
    FIRSTNAME STRING,
    GENDER STRING,
    STATUSID INTEGER,
    CREATEDDATE TIMESTAMP,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_NAMEFIRST ADD CONSTRAINT xpk_DATAEXISTING_NAMEFIRST PRIMARY KEY (FIRSTNAMEID);

DROP TABLE IF EXISTS DATAEXISTING_NAMELAST;
CREATE TABLE DATAEXISTING_NAMELAST (
    LASTNAMEID INTEGER NOT NULL,
    LASTNAME STRING,
    STATUSID INTEGER,
    CREATEDDATE TIMESTAMP,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_NAMELAST ADD CONSTRAINT xpk_DATAEXISTING_NAMELAST PRIMARY KEY (LASTNAMEID);

DROP TABLE IF EXISTS DATAEXISTING_PROFESSION;
CREATE TABLE DATAEXISTING_PROFESSION (
    PROFESSIONID INTEGER NOT NULL,
    PROFESSIONNAME STRING,
    STATUSID INTEGER,
    CREATEDDATE TIMESTAMP,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_PROFESSION ADD CONSTRAINT xpk_DATAEXISTING_PROFESSION PRIMARY KEY (PROFESSIONID);

DROP TABLE IF EXISTS DATAEXISTING_UPCCODES;
CREATE TABLE DATAEXISTING_UPCCODES (
    UPCCODEID INTEGER NOT NULL,
    UPCCODENAME STRING,
    UPCPRODUCTNAME STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_UPCCODES ADD CONSTRAINT xpk_DATAEXISTING_UPCCODES PRIMARY KEY (UPCCODEID);

DROP TABLE IF EXISTS DATAEXISTING_ZIPCODEINTL;
CREATE TABLE DATAEXISTING_ZIPCODEINTL (
    ZIPCODEINTNLID INTEGER NOT NULL,
    ZIPCODE STRING,
    ZIPCODETYPE STRING,
    CITY STRING,
    COUNTRY STRING,
    LATTITUDE STRING,
    LONGITUDE STRING,
    LOCATION STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_ZIPCODEINTL ADD CONSTRAINT xpk_DATAEXISTING_ZIPCODEINTL PRIMARY KEY (ZIPCODEINTNLID);

DROP TABLE IF EXISTS DATAEXISTING_ZIPCODEUS;
CREATE TABLE DATAEXISTING_ZIPCODEUS (
    ZIPCODEID INTEGER NOT NULL,
    ZIPCODE STRING,
    ZIPCODETYPE STRING,
    CITY STRING,
    STATECODE STRING,
    LATTITUDE STRING,
    LONGITUDE STRING,
    LCTN STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAEXISTING_ZIPCODEUS ADD CONSTRAINT xpk_DATAEXISTING_ZIPCODEUS PRIMARY KEY (ZIPCODEID);

DROP TABLE IF EXISTS DATAGENERATED_ACCOUNTNUMBERS;
CREATE TABLE DATAGENERATED_ACCOUNTNUMBERS (
    ACCOUNTNUMBERSID INTEGER NOT NULL,
    ACCOUNTNUMBERVALUE STRING,
    CREATEDDATE TIMESTAMP,
    CREATEDUSER STRING,
    STATUSID INTEGER,
    REGISTEREDAPP STRING,
    DATAGENTYPEID INTEGER
);
ALTER TABLE DATAGENERATED_ACCOUNTNUMBERS ADD CONSTRAINT xpk_DATAGENERATED_ACCOUNTNUMBERS PRIMARY KEY (ACCOUNTNUMBERSID);

DROP TABLE IF EXISTS DATAGENERATED_ADDRESSES;
CREATE TABLE DATAGENERATED_ADDRESSES (
    ADDRESSID INTEGER NOT NULL,
    ADDRESSSTREET STRING,
    ADDRESSSTREET2 STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING,
    DATAGENTYPEID INTEGER
);
ALTER TABLE DATAGENERATED_ADDRESSES ADD CONSTRAINT xpk_DATAGENERATED_ADDRESSES PRIMARY KEY (ADDRESSID);

DROP TABLE IF EXISTS DATAGENERATED_BANKACCOUNT;
CREATE TABLE DATAGENERATED_BANKACCOUNT (
    BANKACCOUNTSID INTEGER NOT NULL,
    BANKACCOUNTVALUE STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING,
    DATAGENTYPEID INTEGER
);
ALTER TABLE DATAGENERATED_BANKACCOUNT ADD CONSTRAINT xpk_DATAGENERATED_BANKACCOUNT PRIMARY KEY (BANKACCOUNTSID);

DROP TABLE IF EXISTS DATAGENERATED_CREDITCARD;
CREATE TABLE DATAGENERATED_CREDITCARD (
    CREDITCARDID INTEGER NOT NULL,
    CREDITCARDNUMBER STRING,
    CREDITCARDNAME STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING,
    DATAGENTYPEID INTEGER
);
ALTER TABLE DATAGENERATED_CREDITCARD ADD CONSTRAINT xpk_DATAGENERATED_CREDITCARD PRIMARY KEY (CREDITCARDID);

DROP TABLE IF EXISTS DATAGENERATED_CUSTOM;
CREATE TABLE DATAGENERATED_CUSTOM (
    DATAGENCUSTOMDID INTEGER NOT NULL,
    CUSTOMIDENTIFIER STRING,
    CUSTOMIDENTIFIERDESC STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING,
    DATAGENTYPEID INTEGER
);
ALTER TABLE DATAGENERATED_CUSTOM ADD CONSTRAINT xpk_DATAGENERATED_CUSTOM PRIMARY KEY (DATAGENCUSTOMDID);

DROP TABLE IF EXISTS DATAGENERATED_DATEOFBIRTH;
CREATE TABLE DATAGENERATED_DATEOFBIRTH (
    DATEOFBIRTHSID INTEGER NOT NULL,
    DATEOFBIRTH STRING,
    DATEOFBIRTHDATE DATE,
    AGE INTEGER,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAGENERATED_DATEOFBIRTH ADD CONSTRAINT xpk_DATAGENERATED_DATEOFBIRTH PRIMARY KEY (DATEOFBIRTHSID);

DROP TABLE IF EXISTS DATAGENERATED_DEVICES;
CREATE TABLE DATAGENERATED_DEVICES (
    DEVICESID INTEGER NOT NULL,
    DEVICENAME STRING,
    DEVICETYPEID INTEGER,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    APPLICATION STRING
);
ALTER TABLE DATAGENERATED_DEVICES ADD CONSTRAINT xpk_DATAGENERATED_DEVICES PRIMARY KEY (DEVICESID);

DROP TABLE IF EXISTS DATAGENERATED_DRIVERSLICENSES;
CREATE TABLE DATAGENERATED_DRIVERSLICENSES (
    DRIVERSLICENSESID INTEGER NOT NULL,
    DLN STRING,
    STATECODE STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    DATAGENTYPEID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAGENERATED_DRIVERSLICENSES ADD CONSTRAINT xpk_DATAGENERATED_DRIVERSLICENSES PRIMARY KEY (DRIVERSLICENSESID);

DROP TABLE IF EXISTS DATAGENERATED_EIN;
CREATE TABLE DATAGENERATED_EIN (
    EINID INTEGER NOT NULL,
    EINVALUE STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAGENERATED_EIN ADD CONSTRAINT xpk_DATAGENERATED_EIN PRIMARY KEY (EINID);

DROP TABLE IF EXISTS DATAGENERATED_PHONENUMBER;
CREATE TABLE DATAGENERATED_PHONENUMBER (
    PHONENUMBERID INTEGER NOT NULL,
    PHONENUMBERVALUE STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAGENERATED_PHONENUMBER ADD CONSTRAINT xpk_DATAGENERATED_PHONENUMBER PRIMARY KEY (PHONENUMBERID);

DROP TABLE IF EXISTS DATAGENERATED_PHONENUMBERSINTL;
CREATE TABLE DATAGENERATED_PHONENUMBERSINTL (
    PHONENUMBERINTLID INTEGER NOT NULL,
    PHONENUMBERVALUE STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    COUNTRYID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAGENERATED_PHONENUMBERSINTL ADD CONSTRAINT xpk_DATAGENERATED_PHONENUMBERSINTL PRIMARY KEY (PHONENUMBERINTLID);

DROP TABLE IF EXISTS DATAGENERATED_REGEXS;
CREATE TABLE DATAGENERATED_REGEXS (
    REGEXID INTEGER NOT NULL,
    REGEXVALUE STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGEXTYPEID INTEGER
);
ALTER TABLE DATAGENERATED_REGEXS ADD CONSTRAINT xpk_DATAGENERATED_REGEXS PRIMARY KEY (REGEXID);

DROP TABLE IF EXISTS DATAGENERATED_SERIALNUMBERS;
CREATE TABLE DATAGENERATED_SERIALNUMBERS (
    SERIALNUMBERID INTEGER NOT NULL,
    SERIALNUMBERVALUE STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAGENERATED_SERIALNUMBERS ADD CONSTRAINT xpk_DATAGENERATED_SERIALNUMBERS PRIMARY KEY (SERIALNUMBERID);

DROP TABLE IF EXISTS DATAGENERATED_SOCIALSECURITYNUMBER;
CREATE TABLE DATAGENERATED_SOCIALSECURITYNUMBER (
    SOCIALSECURITYNUMBERID INTEGER NOT NULL,
    SOCIALSECURITYNUMBERVALUE STRING,
    CREATEDDATE TIMESTAMP,
    STATUSID INTEGER,
    CREATEDUSER STRING,
    REGISTEREDAPP STRING
);
ALTER TABLE DATAGENERATED_SOCIALSECURITYNUMBER ADD CONSTRAINT xpk_DATAGENERATED_SOCIALSECURITYNUMBER PRIMARY KEY (SOCIALSECURITYNUMBERID);

DROP TABLE IF EXISTS DATAGENERATED_USERIDENTITIES;
CREATE TABLE DATAGENERATED_USERIDENTITIES (
     USERIDENTITIESID INTEGER NOT NULL,
     USERIDENTITYVALUE STRING,
     USERDOMAIN STRING,
     ADDITIONALATTRIBUTES STRING,
     CREATEDDATE TIMESTAMP,
     STATUSID INTEGER,
     REGISTEREDAPP STRING,
     DATAGENTYPEID INTEGER
);
ALTER TABLE DATAGENERATED_USERIDENTITIES ADD CONSTRAINT xpk_DATAGENERATED_USERIDENTITIES PRIMARY KEY (USERIDENTITIESID);
